### PR TITLE
Feature/spring hacking

### PR DESCRIPTION
**Pull request by vidstige**

### CODE REVIEW

**Comment by vidstige** [comment]
Please take a look @sumittada 

Found the following nifty url. It does the configuration-combining thing on TeamCity ^^. Can potentially work with ifttt. 

https://build.volumental.com/httpAuth/app/rest/builds/?locator=status:failure,sinceBuild:(status:success)

**Comment by vidstige** [comment]
We just need to wait for a failing build to test it out.

**Comment by vidstige** [comment]
On the downside it checks *all* projects as opposed to specific ones. But I kind of like it anyway.

**Comment by sumittada** [comment]
What about archived projects? Does it ignore them or false for them?

**Comment by vidstige** [comment]
Ignore it seems. Or if you click the link it says `count="0"` at least. The thing is I don't know if it *always* returns 0...

**Comment by vidstige** [comment]
So can we merge this? Our discussion here is mostly unrelated.

**Comment by sumittada** [comment]
Yes! Looks-good-to-me!

**Pull request merged**
